name: pursenal
description: A FOSS, Cross-Platform Money Management App.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.0

environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  drift: ^2.23.1
  drift_flutter: ^0.1.0
  ffi: ^2.1.3
  sqlite3_flutter_libs: ^0.5.28
  path_provider: ^2.1.5
  path: ^1.9.0
  intl: ^0.19.0
  logger: ^2.5.0
  image_picker: ^1.1.2
  collection: ^1.19.0
  shared_preferences: ^2.3.5
  adaptive_theme: ^3.7.0
  fl_chart: ^0.70.2
  pdf: ^3.11.3
  open_filex: ^4.6.0
  excel: ^4.0.6
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.23.1
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"
  package_rename: ^1.9.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon_rounded.png"
  adaptive_icon_foreground: "assets/icons/app_logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_monochrome: "assets/icons/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 128 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  generate: true # Add this line

  assets:
    - assets/fonts/NotoSans-Regular.ttf
    - assets/icons/app_logo.png
    - assets/icons/app_icon_rounded.png

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: MerriWeather
      fonts:
        - asset: assets/fonts/Merriweather-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

package_rename_config:
  android:
    app_name: Pursenal # (String) The display name of the android app
    package_name: Pursenal # (String) The package name of the android app

  ios:
    app_name: Pursenal # (String) The display name of the ios app
    bundle_name: Pursenal # (String) The bundle name of the ios app
    package_name: Pursenal # (String) The product bundle identifier of the ios app

  linux:
    app_name: Pursenal # (String) The window title of the linux app
    package_name: Pursenal # (String) The application id of the linux app
    exe_name: Pursenal # (String) The executable name (binary name) of the linux app

  macos:
    app_name: Pursenal # (String) The product name of the macos app
    package_name: Pursenal # (String) The product bundle identifier of the macos app
    copyright_notice: Pursenal # (String) The product copyright of the macos app

  web:
    app_name: Pursenal # (String) The title of the web app and PWA
    short_app_name: Pursenal # (String) The short display name of the PWA (Optional, defaults to app_name if not set)
    description: A FOSS, Cross-Platform Money Management App. # (String) The description of the web app and PWA

  windows:
    app_name: Pursenal # (String) The window title & software name of the windows app
    organization: Kaashier # (String) The organization name (company name) of the windows app
    exe_name: Pursenal # (String) The executable name (binary name) of the windows app
